version: "3.7"

services:
#  swoole:
#    container_name: swool_wbsocket_php
#    build:
#      context: .
#    user: 1000:1000
#    volumes:
#      - ~/.composer/cache/:/.composer_cache/:rw
#      - .:/app:rw
#    working_dir: /app
#    restart: on-failure
#    command: '/app/bin/console swoole:server:run'
#    ports:
#      - 9501:9501
#      - 9200:9200

  nginx:
    container_name: ${APP_COMPOSE_PROJECT_NAME}_nginx
    image: nginx:alpine
    working_dir: /app
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/app
    ports:
      - 9504:80
      - 8080:8080

  php-fpm:
    container_name: ${APP_COMPOSE_PROJECT_NAME}_php_fpm
    image: brdnlsrg/baseimage:php8.0-full-dev
    env_file:
      - .env
    user: 1000:1000
    ports:
      - "9000:9003"
    environment:
      PHP_IDE_CONFIG: serverName=docker
    volumes:
      - ~/.composer/cache/:/.composer_cache/:rw
      - ./:/app:rw
    working_dir: /app

  swoole_ws:
    container_name: swool_ws_php
    build:
      context: .
    user: 1000:1000
    volumes:
      - ~/.composer/cache/:/.composer_cache/:rw
      - .:/app:rw
    working_dir: /app
    restart: on-failure
    command: '/app/server'
    ports:
      - 9502:9502
