#!/usr/bin/env php
<?php


include __DIR__."/vendor/autoload.php";

use Jtrw\Micro\Poc\Rpc\SwooleWebSocket\WebSocket;

//Add LoggerInterface
$options = [
    'host' => '0.0.0.0',
    'port' => 9502
];
$webSocket = new WebSocket($options);
$webSocket->start();
