imports:
  - { resource: 'parameters.yaml' }

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  ping.json_rpc:
    class: Jtrw\Micro\Poc\Rpc\Presentation\Rpc\PingMethod
    tags:
      - { name: 'json_rpc_http_server.jsonrpc_method', method: 'ping' }
#Jtrw\Micro\Poc\Rpc\:
#  resource: '../src/*'
#  exclude: '../src/{Kernel.php}'
