imports:
  - { resource: 'parameters.yaml' }

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

#Jtrw\Micro\Poc\Rpc\:
#  resource: '../src/*'
#  exclude: '../src/{Kernel.php,Application/Dto/,Domain/Command,Domain/Entity,Domain/Event,Domain/Exception,Domain/Query,Domain/ValueObject,Infrastructure/Migrations,Presentation/Cli}'
